before:
  hooks:
  - go mod download
builds:
- env:
  - CGO_ENABLED=0
  main: ./
  binary: ssh-agent-multiplexer
  goos:
  - linux
  - darwin
  goarch:
  - amd64
  - arm64
  ldflags:
  - -s -w -X main.Version={{.Version}} -X main.Revision={{.ShortCommit}}

dockers:
- image_templates: ["ghcr.io/everpeace/{{ .ProjectName }}:{{ .Version }}-amd64"]
  dockerfile: Dockerfile
  goarch: amd64
  use: buildx
  build_flag_templates:
  - --platform=linux/amd64
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/everpeace/{{ .ProjectName }}
  - --label=org.opencontainers.image.source=https://github.com/everpeace/{{ .ProjectName }}
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.revision={{ .ShortCommit }}
  - --label=org.opencontainers.image.licenses=Apache-2.0
- image_templates: ["ghcr.io/everpeace/{{ .ProjectName }}:{{ .Version }}-arm64v8"]
  goarch: arm64
  dockerfile: Dockerfile
  use: buildx
  build_flag_templates:
  - --platform=linux/arm64/v8
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/everpeace/{{ .ProjectName }}
  - --label=org.opencontainers.image.source=https://github.com/everpeace/{{ .ProjectName }}
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .ShortCommit }}
  - --label=org.opencontainers.image.licenses=Apache-2.0
docker_manifests:
- name_template: ghcr.io/everpeace/{{ .ProjectName }}:{{ .Version }}
  image_templates:
  - ghcr.io/everpeace/{{ .ProjectName }}:{{ .Version }}-amd64
  - ghcr.io/everpeace/{{ .ProjectName }}:{{ .Version }}-arm64v8
- name_template: ghcr.io/everpeace/{{ .ProjectName }}:latest
  image_templates:
  - ghcr.io/everpeace/{{ .ProjectName }}:latest-amd64
  - ghcr.io/everpeace/{{ .ProjectName }}:latest-arm64v8

release:
  prerelease: auto
