name: release
description: release executables

inputs:
  tag:
    description: check out the tag if not empty
    default: ''
  token:
    description: GitHub token
    required: true

runs:
  using: composite

  steps:
  - uses: actions/checkout@v3
    name: "checkout tag ${{ inputs.tag }}"
    if: "inputs.tag != ''"
    with:
      ref: refs/tags/${{ inputs.tag }}
    env:
      GITHUB_TOKEN: ${{ inputs.token }}
  - name: Set up Go
    uses: actions/setup-go@v3
    with:
      go-version-file: go.mod
  - name: Login to GitHub Container Registry
    uses: docker/login-action@v2
    with:
      registry: ghcr.io
      username: everpeace
      password: ${{ inputs.token }}
  - name: Run GoReleaser
    uses: goreleaser/goreleaser-action@v6
    with:
      args: release --clean
    env:
      GITHUB_TOKEN: ${{ inputs.token }}
