name: CI

on:
  push:
    branches: [ main ]
    tags-ignore: [ "**" ]
    paths-ignore: [ "**.md" ]
  pull_request:
    types: [opened, synchronize]
    paths-ignore: [ "**.md" ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ~1.19
      id: go
    - name: Check out
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Get dependencies
      run: go mod download
    - name: Get Devtools
      run: make setup
    - name: Lint
      run : make lint
    - name: Build
      run: make
    # - name: Test
    #   run: make test
    - name: Validate .goreleaser.yml
      uses: goreleaser/goreleaser-action@v3
      with:
        version: latest
        args: release --snapshot --skip-publish --rm-dist --debug
