name: CI

on:
  push:
    branches: [ main ]
    tags-ignore: [ "**" ]
    paths-ignore: [ "**.md" ]
  pull_request:
    types: [opened, synchronize]
    paths-ignore: [ "**.md" ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version-file: go.mod
      id: go
    - name: Get dependencies
      run: go mod download
    - name: Get Devtools
      run: make setup
    - name: Lint
      run : make lint
    - name: Build
      run: make
    - name: Run unit tests
      run: make test
    - name: Validate .goreleaser.yml
      uses: goreleaser/goreleaser-action@v6
      with:
        version: '~> v2'
        args: release --snapshot --skip=publish --clean --verbose
