name: Release By Tagged Manually
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  goreleaser:
    name: Release Binaries And Docker Images
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate ssh-agent-multiplexer-releaser-bot token
        id: generate-releaser-bot-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.RELEASER_BOT_APP_ID }}
          private-key: ${{ secrets.RELEASER_BOT_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      - uses: ./.github/actions/release
        with:
          tag: ${{ github.ref_name }}
          token: ${{ steps.generate-releaser-bot-token.outputs.token }}
