#
# tagpr main workflow
#
name: tagpr
on:
  push:
    branches: ["main"]

jobs:
  tagpr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - id: tagpr
      name: Tagpr
      uses: Songmu/tagpr@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # If tagpr pushed tags, invoke release custom action manually.
      # It is because:
      # > When you use the repository's GITHUB_TOKEN to perform tasks, 
      # > events triggered by the GITHUB_TOKEN, with the exception of 
      # > workflow_dispatch and repository_dispatch, will not create 
      # > a new workflow run.
      # ref: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow
    - name: Generate ssh-agent-multiplexer-releaser-bot token
      id: generate-releaser-bot-token
      uses: actions/create-github-app-token@v2
      with:
        app-id: ${{ vars.RELEASER_BOT_APP_ID }}
        private-key: ${{ secrets.RELEASER_BOT_PRIVATE_KEY }}
    - name: "Release (only when tagged)"
      uses: ./.github/actions/release
      if: "steps.tagpr.outputs.tag != ''"
      with:
        tag: ${{ steps.tagpr.outputs.tag }}
        token: ${{ steps.generate-releaser-bot-token.outputs.token }}
